networks:
  dialogue-service-nw:
    driver: bridge

services:
  backend:
    container_name: backend
    image: dialogue-service:0.1.0
    build:
      context: ./
      dockerfile: service.Dockerfile
    networks:
      - dialogue-service-nw
    ports:
      - "8082:8082"
