networks:
  dialogue-service-nw:
    name: dialogue-service-nw
    driver: bridge
  interservice-nw:
    name: interservice-nw
    driver: bridge
  kafka-nw:
    name: kafka-nw
    driver: bridge

services:
  backend:
    container_name: dialogue-service-backend
    image: dialogue-service:0.2.0
    build:
      context: ./
      dockerfile: service.Dockerfile
    networks:
      - dialogue-service-nw
      - interservice-nw
      - kafka-nw
    ports:
      - "28084:8084"
