version: '3'

tasks:
  gen-pb:
    desc: Generate *.pb.go files
    cmds:
      - protoc --proto_path ./api --go_out ./internal/proto/dialogue/ --go_opt paths=source_relative --go-grpc_out ./internal/proto/dialogue/ --go-grpc_opt paths=source_relative ./api/dialogue.proto

  run:
    desc: Run the service
    cmds:
      - go run ./cmd/app/main.go --config ./configs/local.yml

  compose-service-up:
    desc: Up the container of the service
    cmds:
      - docker compose -f ./docker-compose-service.yml up -d

  compose-service-down:
    desc: Down the container of the service
    cmds:
      - docker compose -f ./docker-compose-service.yml down

  compose-infra-up:
    desc: Up infrastructure containers
    cmds:
      - docker compose -f ./docker-compose-infra.yml up -d

  compose-infra-down:
    desc: Down infrastructure containers
    cmds:
      - docker compose -f ./docker-compose-infra.yml down

  migrate-up:
    desc: Migrate database up
    cmds:
      - goose -dir ./migrations/ postgres "host=localhost port=25432 user=postgres dbname=postgres" up

  migrate-down:
    desc: Migrate database down
    cmds:
      - goose -dir ./migrations/ postgres "host=localhost port=25432 user=postgres dbname=postgres" down

